# Generated by Django 4.2.13 on 2024-05-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coders_cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
