# Generated by Django 4.2.13 on 2024-06-02 11:19

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coders_cafe', '0002_rename_user_id_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(19)]),
        ),
    ]
